"use client";
import { useEffect, useMemo, useState } from "react";
import "./search.css";

type Produto={id:string;codigo:string;descricao:string;unidade:string;classificacao:string;classificacaoGeral:string;produtoAcabado:string};
const KEY="prodpcp-produtos";
export default function PesquisaProdutos(){
 const[items,setItems]=useState<Produto[]>([]); const[search,setSearch]=useState(""); const[fClass,setFClass]=useState(""); const[fGeral,setFGeral]=useState("");
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||"[]"))}catch{setItems([])}},[]);
 const classes=useMemo(()=>Array.from(new Set(items.map(x=>x.classificacao).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR")),[items]);
 const gerais=useMemo(()=>Array.from(new Set(items.map(x=>x.classificacaoGeral).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR")),[items]);
 const filtered=useMemo(()=>{const q=search.toLocaleLowerCase("pt-BR").trim();return items.filter(x=>(!q||[x.codigo,x.descricao,x.unidade,x.classificacao,x.classificacaoGeral,x.produtoAcabado].some(v=>v.toLocaleLowerCase("pt-BR").includes(q)))&&(!fClass||x.classificacao===fClass)&&(!fGeral||x.classificacaoGeral===fGeral))},[items,search,fClass,fGeral]);
 const totalByClass=(c:string)=>items.filter(x=>x.classificacao===c).length;
 return <div className="app-shell"><aside className="sidebar"><img src="/prodpcp-logo.svg" alt="ProdPCP" className="logo"/><div className="menu-label">Cadastros</div><a className="menu-item" href="/cadastros/clientes-fornecedores"><span className="menu-icon">▦</span><span>Clientes e Fornecedores</span></a><a className="menu-item active" href="/cadastros/produtos"><span className="menu-icon">▤</span><span>Produtos</span></a><a className="menu-item" href="/cadastros/produtos/pesquisa"><span className="menu-icon">⌕</span><span>Pesquisa</span></a></aside><main className="main"><header className="topbar"><div className="breadcrumb">Cadastros &nbsp;/&nbsp; Produtos &nbsp;/&nbsp; <strong>Pesquisa</strong></div><div className="user-chip"><span className="avatar">PCP</span> ProdPCP</div></header><section className="content"><div className="page-heading"><h1>Pesquisa de Produtos</h1><p>Consulte, filtre e edite os produtos cadastrados.</p></div><div className="card"><div className="search-bar"><div className="search-input"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por código, descrição, classificação..."/></div><a className="btn btn-primary" href="/cadastros/produtos">+ Novo produto</a></div><div className="filters"><select value={fClass} onChange={e=>setFClass(e.target.value)}><option value="">Todas as classificações</option>{classes.map(x=><option key={x}>{x}</option>)}</select><select value={fGeral} onChange={e=>setFGeral(e.target.value)}><option value="">Todas as classificações gerais</option>{gerais.map(x=><option key={x}>{x}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Código</th><th>Descrição</th><th>Unidade</th><th>Classificação</th><th>Classificação Geral</th><th>Qtde Total por Classificação</th><th>Acabado?</th><th></th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td><strong>{x.codigo}</strong></td><td>{x.descricao}</td><td>{x.unidade}</td><td>{x.classificacao}</td><td>{x.classificacaoGeral}</td><td>{totalByClass(x.classificacao)}</td><td>{x.produtoAcabado}</td><td><a className="edit-link" href={`/cadastros/produtos?edit=${x.id}`}>Editar</a></td></tr>):<tr><td colSpan={8} className="empty-state">Nenhum produto encontrado.</td></tr>}</tbody></table></div><div className="table-footer">{filtered.length} produto(s) encontrado(s)</div></div></section></main></div>
}