"use client";
import { useEffect, useMemo, useState } from "react";
import "../page.css";

type Vinculo={id:string;codigoBelmonte:string;codigoFornecedorObra:string;unidade:string;descricao:string;obra:string;numeroPedido:string;tipoMaterial:string};
const KEY="prodpcp-produtos-obras";
const norm=(v:string)=>v.trim().toLocaleLowerCase("pt-BR");
export default function PesquisaClientesProdutos(){
 const[items,setItems]=useState<Vinculo[]>([]);const[search,setSearch]=useState("");
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||"[]"))}catch{setItems([])}},[]);
 const filtered=useMemo(()=>{const q=norm(search);return items.filter(x=>!q||[x.codigoBelmonte,x.codigoFornecedorObra,x.unidade,x.descricao,x.obra,x.numeroPedido,x.tipoMaterial].some(v=>norm(v).includes(q)))},[items,search]);
 return <div className="app-shell"><aside className="sidebar"><img src="/prodpcp-logo.svg" alt="ProdPCP" className="logo"/><div className="menu-label">Cadastros</div><a className="menu-item" href="/cadastros/clientes-fornecedores"><span className="menu-icon">▦</span><span>Clientes e Fornecedores</span></a><a className="menu-item" href="/cadastros/clientes-fornecedores/pesquisa"><span className="menu-icon">⌕</span><span>Pesquisa</span></a><a className="menu-item" href="/cadastros/produtos"><span className="menu-icon">▤</span><span>Produtos</span></a><a className="menu-item" href="/cadastros/produtos/pesquisa"><span className="menu-icon">⌕</span><span>Pesquisa</span></a><a className="menu-item" href="/cadastros/produtos-obras"><span className="menu-icon">⇄</span><span>Clientes x Produtos</span></a><a className="menu-item active" href="/cadastros/produtos-obras/pesquisa"><span className="menu-icon">⌕</span><span>Pesquisa</span></a></aside><main className="main"><header className="topbar"><div className="breadcrumb">Cadastros &nbsp;/&nbsp; Clientes x Produtos &nbsp;/&nbsp; <strong>Pesquisa</strong></div><div className="user-chip"><span className="avatar">PCP</span> ProdPCP</div></header><section className="content"><div className="page-heading"><h1>Pesquisa de Clientes x Produtos</h1><p>Consulte os produtos vinculados às obras e fornecedores.</p></div><div className="card"><div className="search-bar"><div className="search-input"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por código, descrição, obra, pedido ou material..."/></div><a className="btn btn-primary" href="/cadastros/produtos-obras">+ Novo vínculo</a></div><div className="table-wrap"><table><thead><tr><th>Cód. BELMONTE</th><th>Cód. Forn/Obra</th><th>Descrição</th><th>Unidade</th><th>Obra</th><th>Nº Ped.</th><th>Material</th><th></th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td><strong>{x.codigoBelmonte}</strong></td><td>{x.codigoFornecedorObra}</td><td>{x.descricao}</td><td>{x.unidade}</td><td>{x.obra}</td><td>{x.numeroPedido||"—"}</td><td>{x.tipoMaterial}</td><td><a className="edit-link" href={`/cadastros/produtos-obras?edit=${x.id}`}>Editar</a></td></tr>):<tr><td colSpan={8} className="empty-state">Nenhum vínculo encontrado.</td></tr>}</tbody></table></div><div className="table-footer">{filtered.length} vínculo(s) encontrado(s)</div></div></section></main></div>}
