"use client";

import { FormEvent, useState } from "react";

const SMALL_WORDS = new Set(["de", "da", "do", "das", "dos", "e", "em", "com", "por", "para"]);
function properCase(value: string) { return value.toLocaleLowerCase("pt-BR").trim().split(/\s+/).map((word, index) => index > 0 && SMALL_WORDS.has(word) ? word : word.charAt(0).toLocaleUpperCase("pt-BR") + word.slice(1)).join(" "); }
function formatCnpj(value: string) { const d = value.replace(/\D/g, "").slice(0, 14); return d.replace(/^(\d{2})(\d)/, "$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/, "$1.$2.$3").replace(/\.(\d{3})(\d)/, ".$1/$2").replace(/(\d{4})(\d)/, "$1-$2"); }
function formatPhone(value: string) { const d = value.replace(/\D/g, "").slice(0, 11); return d.length <= 10 ? d.replace(/^(\d{2})(\d)/, "($1) $2").replace(/(\d{4})(\d)/, "$1-$2") : d.replace(/^(\d{2})(\d)/, "($1) $2").replace(/(\d{5})(\d)/, "$1-$2"); }
function isValidCnpj(value: string) { const d = value.replace(/\D/g, ""); if (d.length !== 14 || /^(\d)\1+$/.test(d)) return false; const calc = (length: number) => { let sum = 0, weight = length - 7; for (let i = 0; i < length; i++) { sum += Number(d[i]) * weight; weight = weight === 2 ? 9 : weight - 1; } const r = sum % 11; return r < 2 ? 0 : 11 - r; }; return calc(12) === Number(d[12]) && calc(13) === Number(d[13]); }

type Form = { cnpj:string; razaoSocial:string; nomeFantasia:string; numeroObra:string; endereco:string; bairro:string; municipio:string; responsavel:string; telefone:string; tipoMaterial:string; clienteObra:string; tipoCadastro:string };
const empty: Form = { cnpj:"", razaoSocial:"", nomeFantasia:"", numeroObra:"", endereco:"", bairro:"", municipio:"", responsavel:"", telefone:"", tipoMaterial:"", clienteObra:"", tipoCadastro:"" };

export default function ClientesFornecedoresPage() {
 const [form,setForm]=useState<Form>(empty); const [message,setMessage]=useState<string|null>(null);
 const update=(field:keyof Form,value:string)=>{setMessage(null);setForm(c=>({...c,[field]:value}));};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!isValidCnpj(form.cnpj))return setMessage("Informe um CNPJ válido.");if(!form.razaoSocial.trim()||!form.nomeFantasia.trim()||!form.municipio.trim()||!form.tipoMaterial||!form.tipoCadastro)return setMessage("Preencha os campos obrigatórios.");setMessage("Cadastro validado com sucesso. A gravação no banco será conectada na próxima etapa.");};
 return <div className="app-shell"><aside className="sidebar"><img src="/prodpcp-logo.svg" alt="ProdPCP" className="logo"/><div className="menu-label">Cadastros</div><a className="menu-item active" href="/cadastros/clientes-fornecedores"><span className="menu-icon">▦</span><span>Clientes e Fornecedores</span></a><a className="menu-item" href="/cadastros/clientes-fornecedores/pesquisa"><span className="menu-icon">⌕</span><span>Pesquisa</span></a></aside><main className="main"><header className="topbar"><div className="breadcrumb">Cadastros &nbsp;/&nbsp; <strong>Clientes e Fornecedores</strong></div><div className="user-chip"><span className="avatar">PCP</span> ProdPCP</div></header><section className="content"><div className="page-heading"><h1>Cadastro de Clientes e Fornecedores</h1><p>Cadastre os dados comerciais e classifique o relacionamento.</p></div><div className="card"><div className="card-header"><div><h2 className="card-title">Dados cadastrais</h2><div className="card-subtitle">Campos marcados com <span className="required">*</span> são obrigatórios.</div></div></div><form className="form" onSubmit={submit}><div className="grid">
 {([['cnpj','CNPJ *'],['razaoSocial','Razão Social *'],['nomeFantasia','Nome Fantasia *'],['numeroObra','Nº Obra'],['endereco','Endereço'],['bairro','Bairro'],['municipio','Município *'],['responsavel','Responsável'],['telefone','Telefone'],['clienteObra','Cliente / Obra']] as const).map(([key,label])=><div key={key} className={`field ${key==='razaoSocial'||key==='nomeFantasia'||key==='endereco'?'span-8':''}`}><label>{label}</label><input value={form[key]} onChange={e=>update(key,key==='cnpj'?formatCnpj(e.target.value):key==='telefone'?formatPhone(e.target.value):e.target.value)} onBlur={e=>{if(!['cnpj','telefone','numeroObra'].includes(key))update(key,properCase(e.target.value));}} /></div>)}
 <div className="field"><label>Tipo de Material *</label><div className="type-group">{['Ferro','Alumínio','Ambos'].map(t=><button key={t} type="button" className={`type-option ${form.tipoMaterial===t?'selected':''}`} onClick={()=>update('tipoMaterial',t)}>{t}</button>)}</div></div><div className="field"><label>Tipo de Cadastro *</label><select value={form.tipoCadastro} onChange={e=>update('tipoCadastro',e.target.value)}><option value="">Selecione</option><option>Obra</option><option>Fornecedor</option><option>Belmonte</option></select></div>
 </div><div className="actions"><button className="btn" type="button" onClick={()=>{setForm(empty);setMessage(null);}}>Limpar</button><button className="btn btn-primary" type="submit">Cadastrar</button></div></form>{message&&<div className={`message ${message.includes('sucesso')?'success':'error'}`}>{message}</div>}</div></section></main></div>;
}
